export const brands = [
  {
    src: "binance.svg",
    width: 154,
    height: 40,
    classnames: [""],
  },
  {
    src: "spartan.svg",
    width: 157,
    height: 45,
    classnames: [""],
  },
  {
    src: "shima.svg",
    width: 104,
    height: 58,
    classnames: [""],
  },
  {
    src: "labs.svg",
    width: 89,
    height: 39,
    classnames: [""],
  },
  {
    src: "captical.svg",
    width: 139,
    height: 30,
    classnames: [""],
  },
  {
    src: "you.svg",
    width: 142,
    height: 35,
    classnames: [""],
  },
  {
    src: "amber.svg",
    width: 96,
    height: 16,
    classnames: [""],
  },
  {
    src: "snz.svg",
    width: 64,
    height: 35,
    classnames: ["center"],
  },
  {
    src: "cmtd.svg",
    width: 172,
    height: 29,
    classnames: [""],
  },
  {
    src: "avatvr.svg",
    width: 113,
    height: 20,
    classnames: [""],
  },
  {
    src: "sevenx.svg",
    width: 127,
    height: 34,
    classnames: [""],
  },
  {
    src: "bubit.svg",
    width: 96,
    height: 35,
    classnames: [""],
  },
  {
    src: "maplebl.svg",
    width: 143,
    height: 25,
    classnames: [""],
  },
  {
    src: "DoraHacksVentures.svg",
    width: 126,
    height: 40,
    classnames: [""],
  },
  {
    src: "crasolum.svg",
    width: 140,
    height: 24,
    classnames: [""],
  },
  {
    src: "block0.svg",
    width: 100,
    height: 28,
    classnames: [""],
  },
  {
    src: "looprlnc.svg",
    width: 131,
    height: 36,
    classnames: [""],
  },
  {
    src: "cmccgloba.svg",
    width: 163,
    height: 19,
    classnames: [""],
  },
  {
    src: "cypherpunn.svg",
    width: 115,
    height: 36,
    classnames: [""],
  },
  {
    src: "stake.svg",
    width: 75,
    height: 32,
    classnames: [""],
  },
  {
    src: "20.svg",
    width: 132,
    height: 24,
    classnames: [""],
  },
  {
    src: "21.svg",
    width: 110,
    height: 31,
    classnames: [""],
  },
  {
    src: "stratified.png",
    width: 136,
    height: 36,
    classnames: [""],
  },
  {
    src: "spark.svg",
    width: 127,
    height: 36,
    classnames: [""],
  },
  {
    src: "mulana.png",
    width: 110,
    height: 66,
    classnames: ["lower"],
  },
  {
    src: "gate.io.svg",
    width: 105,
    height: 40,
    classnames: [""],
  },
  {
    src: "",
    width: 110,
    height: 39,
    classnames: [""],
  },
  {
    src: "",
    width: 110,
    height: 39,
    classnames: [""],
  },
  {
    src: "",
    width: 110,
    height: 39,
    classnames: [""],
  },
];
